### ISSUE TITLE
Bower

### ISSUE THREAD

**Issue by thegounet** [dec/angular-canvas-gauge#1]
Good work ! 

can i suggest you to register a bower package ? 

[MORE HERE](http://bower.io/docs/creating-packages/#register)

**Comment by thegounet** [comment]
I noticed canv-gauge to do the same, then i'll add it as dependency.

**Comment by Mikhus** [comment]
canv-gauge added to bower already, so feel free to go with adding this package... there is also another issue exists here as far as angular code dependent on the canv-gauge code itself, probably it should be excluded from this repository and dependency managed somehow. Via bower deps or by using git submodules or subtree merges to have it automatically up-to-date... And I'm not the person who is managed to handle this, so, please, @dec, do your best when you have a free time. Thank you in advance!

**Comment by thegounet** [comment]
Thanks for reply.

I'll make the bower package when I'll have some free time. I'll use
canv-gauge as dependency. So I'll refactor a little.
Happy to contribute to your project.
I think it can be useful for lot's of people who use bower.
Le 1 mars 2016 10:47 AM, "Mykhailo Stadnyk" <notifications@github.com> a
écrit :

**Comment by thegounet** [comment]
Done 

waiting for merge and tag

**Comment by Mikhus** [comment]
@thegounet Thanks for a good work! BTW, this repo is owned by @dec, so let's wait for his opinion, review and reaction :)

**Comment by dec** [comment]
@Mikhus done! :-)
